name: Build VPK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-vita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # QUESTA Ãˆ LA RIGA CHE ABBIAMO CORRETTO:
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake

    - name: Build
      run: cmake --build build

    - name: Upload VPK
      uses: actions/upload-artifact@v4
      with:
        name: VitaIPTV-App
        path: build/*.vpk
